Nop.Plugin.Widgets.mobSocial/Controllers/Admin/TeamPageController.cs
using Nop.Services.Security;

namespace Nop.Plugin.Widgets.MobSocial.Controllers.Admin
{
    public partial class TeamPageController : BaseAdminController
    {
        
        #region Fields
        private readonly ITeamPageService _teamPageService;
        private readonly IPermissionService _permissionService;
        #endregion

        #region Constructors

        public TeamPageController(IPermissionService permissionService, ITeamPageService teamPageService)
        {
            _permissionService = permissionService;
            _teamPageService = teamPageService;
        }

        #endregion


        #region Methods

        [AdminAuthorize]
        public IActionResult Index()
        {
            return View(ControllerUtil.MobSocialViewsFolder + "/Views/mobSocial/Admin/ManageTeamPage/List.cshtml");
        }
       
        #endregion


    }
}

Nop.Plugin.Widgets.mobSocial/Controllers/TeamPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Widgets.MobSocial.Models;

namespace Nop.Plugin.Widgets.MobSocial.Controllers
{
    public class TeamPageController : MobSocialWidgetBaseController
    {
        public IActionResult Index(int teamId)
        {
            var model = new TeamPageModel()
            {
                Id = teamId
            };
            return View("mobSocial/TeamPage/Index", model);
        }
        [Authorize]
        public IActionResult TeamPageEditor(int id = 0)
        {
            var model = new TeamPageEditorModel()
            {
                Id = id
            };

            return View("mobSocial/TeamPage/TeamPageEditor", model);
        }
        [Authorize]
        public IActionResult MyPages()
        {
            return View("mobSocial/TeamPage/MyPages");
        }
    }
}

Nop.Plugin.Widgets.mobSocial/Controllers/mobSocialController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Plugin.Widgets.MobSocial.Helpers;
using Nop.Plugin.Widgets.MobSocial.Sdk;


namespace Nop.Plugin.Widgets.MobSocial.Controllers
{
    
    public class MobSocialController : MobSocialWidgetBaseController
    {

        private readonly IWorkContext _workContext;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public MobSocialController(IWorkContext workContext, IHttpContextAccessor httpContextAccessor)
        {
            _workContext = workContext;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            return View("mobSocial/Social/Index");
        }

        [HttpPost]
        public IActionResult AccessToken()
        {
            //get the token
            var customer = _workContext.CurrentCustomer;
            var accessToken = MobSocialClientHelper.NewClient().AccessToken(customer?.Email);
            _httpContextAccessor.HttpContext.Response.Cookies.Append(".MobSocial.ApiAuthentication", accessToken, new CookieOptions()
            {
                Domain = MobSocialClient.Domain,
                HttpOnly = false
            });
            if (customer.IsGuest())
            {
                //prefix with app_ to identify if it's app only token
                accessToken = "app_" + accessToken;
            }
            return Json(new {success = true, access_token = accessToken});
        }
    }





}

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/AddCustomerAlbumPicture.cshtml
@{
    Html.AddCssFileParts("~/Scripts/fineuploader/fineuploader-4.2.2.min.css");
    Html.AddScriptParts("~/Scripts/fineuploader/jquery.fineuploader-4.2.2.min.js");  
}

<style type="text/css">
    
    
</style>

@section left
{
    
    <div class="team-picture">
        <img class="team-picture" src="@Model.TeamPictureUrl" alt="@Model.TeamName" title="@Model.TeamName" />
    </div>

}

<div class="page team-page">
    <div class="page-body">
      
        <div class="team-container">
    
            
    
            <h1>@Model.TeamName</h1>

            <p class="team-description">@Model.TeamDescription</p>
            
            
            
            @foreach (var group in Model.Groups)
            {
                <div class="group-container">
                    <h2>@group.Name</h2>
                    
                    
                    <div class="group-members-container">
                        
                    

                        @foreach (var member in group.Members)
                        {
                            <div class="team-member-picture">
                                <a href="@member.ProfileUrl">
                                    <img src="@member.ThumbnailUrl" alt="@member.DisplayName" title="@member.DisplayName" />
                                    <div class="team-member-name">@member.DisplayName</div>

                                </a>
                                
                            </div>
                        }
        
                        <p class="team-group-description">@group.Description</p>
                    </div>
                            
                </div>
            }
    


        </div>
    </div>
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/MyHealth.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.FriendRequestsModel
@{
    Layout = "~/Views/Shared/_ColumnsTwo.cshtml";

    //title
    Html.AddTitleParts(T("PageTitle.Account").Text);
    
}

@section left
{
    @*todo Add account navigation back 
        @Html.Partial("~/Views/Customer/MyAccountNavigation.cshtml", null, new ViewDataDictionary())*@

    @Html.Action("PublicInfo", "SocialNetworkNavigation", new { widgetZone = "account_navigation_after" })

}
<div class="page account-page order-list-page">
    <div class="page-title">
        <h1>@T("Account.MyAccount") - Friend Requests</h1>
    </div>
    <div class="clear">
    </div>
    <div class="page-body">
  
        <div class="customer-friends-container">
            
            @if(Model.FriendRequests.Count > 0)
            {
                foreach (var friend in Model.FriendRequests)
                {
                    <div class="customer-friend-request-block">
                        <a href="@friend.ProfileUrl">
                            <img src="@friend.ProfileThumbnailUrl" alt="@friend.CustomerDisplayName" title="@friend.CustomerDisplayName" />
                        </a>
                        <span>
                            @Html.Action("AddFriendButton", "MobSocial", new { toCustomerId = friend.FriendId })
                        </span>
                    </div>
                }
            }
            else
            {
                <span class="no-friend-requests-message">You have no friend requests.</span>
            }
        </div>
        
        
        @*<a href="@Url.HttpRouteUrl("PopulateUrlSlugs", "MobSocial")">Populate Url Slugs</a>*@

    </div>
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/ProfileInformation.cshtml
@using Nop.Web.Framework.UI

@model Nop.Plugin.WebApi.MobSocial.Models.ProfileInformationModel
@{
    Layout = "~/Views/Shared/_ColumnsTwo.cshtml";

    //title
    Html.AddTitleParts(T("PageTitle.Account").Text);
}

@section left
{
    @Html.Partial("~/Views/Customer/MyAccountNavigation.cshtml", Model.NavigationModel, new ViewDataDictionary())

    @Html.Action("SocialNetworkNavigation", "MobSocial", new { NavigationModel = Model.NavigationModel })

}
<div class="page account-page order-list-page">
    <div class="page-title">
        <h1>@T("Account.MyAccount") - Profile Info</h1>
    </div>
    <div class="clear">
    </div>
    <div class="page-body">
  
        <div class="">
            
           
          
        </div>

    </div>
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/TeamPage.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.TeamPage.TeamPageModel

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    Html.AppendTitleParts(Model.TeamName);

}


<div class="page team-page">
    <div class="page-body">
      
        <div class="team-container">
    
            
    
            <h1>@Model.TeamName</h1>

            <p class="team-description">@Model.TeamDescription</p>
            
            
            
            @foreach (var group in Model.Groups)
            {
                <div class="group-container">
                    <h2>@group.Name</h2>
                    
                    
                    <div class="group-members-container">
                        
                    

                        @foreach (var member in group.Members)
                        {
                            <div class="team-member-picture">
                                <a href="@member.ProfileUrl">
                                    <img src="@member.ThumbnailUrl" alt="@member.DisplayName" title="@member.DisplayName" />
                                    <div class="team-member-name">@member.DisplayName</div>

                                </a>
                                
                            </div>
                        }
        
                        <p class="team-group-description">@group.Description</p>
                    </div>
                            
                </div>
            }
    


        </div>
    </div>
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/TeamPage_old.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.TeamPage.TeamPageModel


<div class="team-container">
    
    <div class="team-picture">
        <img src="@Model.TeamPictureUrl" alt="@Model.TeamName" title="@Model.TeamName" />
    </div>
    
    <h1>@Model.TeamName</h1>

    <p class="team-description">@Model.TeamDescription</p>

    @foreach (var group in Model.Groups)
    {
        <h2>@group.Name</h2>
        
        foreach (var member in group.Members)
        {
            <div class="team-member-picture">
                <a href="@member.ProfileUrl">
                    <img src="@member.ThumbnailUrl" alt="@member.DisplayName" title="@member.DisplayName" />
                </a>
                @member.DisplayName
            </div>
        }
        
        <p class="team-group-description">@group.Description</p>
        
    }
    


</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_AddFriendButton.cshtml
@model Nop.Plugin.Widgets.MobSocial.Models.AddFriendButtonModel


@{
    Html.AddScriptParts("~/Plugins/Widgets.mobSocial/Content/mobSocial/add-friend-button.js");
}


@if (Model.ShowAddFriendButton || Model.ShowFriendRequestSent)
{
    <div class="addFriendContainer">

        <div id="add-friend-button-container" class="profile-stat @(Model.ShowAddFriendButton ? "show" : "hide")">
            <button class="add-friend-button pm-link-button" data-tocustomerid="@Model.CustomerProfileId"><i class="fa fa-user-plus"></i> @(T("MobSocial.AddFriendButtonText").Text)</button>
        </div>

        <div id="friend-request-sent-container" data-friendcustomerid="@Model.CustomerProfileId" class="profile-stat @(Model.ShowFriendRequestSent ? "show" : "hide")">
            <button>
                <i class="fa fa-check"></i>
                <span id="friend-request-sent" class="friend-request-sent-label">@T("MobSocial.FriendRequestSentLabel")&nbsp;</span>
            </button>
        </div>

    </div>

}
else if (Model.ShowFriendsButton)
{
    <div class="profile-stat">
        <button>
            <i class="fa fa-check"></i>
            <span id="friends-button" class="friend-button">@T("MobSocial.FriendsLabelText")</span>
        </button>
    </div>
}
else if (Model.ShowConfirmFriendButton)
{
    <div class="profile-stat" data-showconfirmbutton="true" data-friendcustomerid="@Model.CustomerProfileId">
        <button>
            <span class="confirm-friend-button friend-button" data-friendcustomerid="@Model.CustomerProfileId">@T("MobSocial.ConfirmFriendButtonText")</span>
            <i class="fa fa-check confirmed-friend-button"></i>
            <span class="confirmed-friend-button friend-button">Confirmed</span>
        </button>
    </div>
}

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_AppColumnsTwo.cshtml
@{
    Layout = "~/Views/Shared/_ColumnsTwo.cshtml";
    var showBox = true;
}
@section left
{
    @if (IsSectionDefined("left"))
    {
        @RenderSection("left")
    }
    else
    {
        @Html.Action("PublicInfo", "SocialNetworkNavigation", new { widgetZone = "account_navigation_after" })

    }
}

<div ng-app="mobSocialApp" class="mobsocialapp" ng-cloak>
    @RenderBody()

    @if (showBox)
    {
        @Html.Partial("~/Plugins/Widgets.MobSocial/Views/mobSocial/Conversation/ConversationBox.cshtml", false)
    }
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_AppLayoutTheater.cshtml
@{
    Layout = "~/Views/Shared/_Root.Head.cshtml";
}
<div ng-app="mobSocialApp" ng-cloak>
    <div class="theater-page-bg">
        @RenderBody()
    </div>
    @Html.Widget("footer")
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_CustomerAlbumPictures.cshtml
@model CustomerAlbumModel

@{
    
}

<div id="dialog-ok"></div>

<div id="dialog-modal" title="Upload Picture">
    Choose a picture to upload:
    
    @using (Ajax.BeginForm("UploadAlbumPicture", "MobSocial", new AjaxOptions() { HttpMethod = "POST" }, new { id = "uploadPictureForm", enctype = "multipart/form-data" }))
    {
        <input type="hidden" name="albumId" value="@Model.AlbumId"/>
        <img id="previewPicture" src="#" alt="Picture Preview" width="190" />
        <input type="file" name="pictureFile" />
        <br/><br/>
        
    }

</div>

<div id="dialog-confirm" title="Delete Picture?">Are you sure you want to delete this picture?</div>

<div class="customer-album-container">
    
    <div class="add-picture-button">
        <i class="fa fa-camera"></i>
        <span class="add-picture-button-text" title="Add Picture">Add Picture</span>
    </div>

    @foreach (var picture in Model.Pictures)
    {
        <div class="customer-album-picture-block" data-customerAlbumPictureId="@picture.Id">
           
                <span class="delete-picture-button" data-customerAlbumPictureId="@picture.Id" title="Delete Picture"><i class="fa fa-trash-o"></i></span>

                <a href="@picture.Url" title="@picture.Caption" data-gallery="lightbox-p"><img src="@picture.ThumbnailUrl" alt="@picture.AltText" title="@picture.AltText" /></a>
                <br/>
                <span class="customer-album-picture-caption">@picture.Caption</span>
            
        </div>
    }
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_CustomerFriendBlock.cshtml
@model List<Nop.Plugin.WebApi.MobSocial.Models.CustomerFriendModel>


<script type="text/javascript">
    $(document).ready(function() {
        $('.view-all-friends-link').click(function() {
            $('#tabs').tabs("option", "active", 3);
        });
    });
</script>
    
<div class="info-friend-block-container">
    
    @if (Model.Count > 0)
    { 
        foreach (var friend in Model)
        {
            <div class="info-friend-block-picture">
                <a href="@friend.ProfileUrl">
                    <img src="@friend.ProfileThumbnailUrl" alt="@friend.CustomerDisplayName" title="@friend.CustomerDisplayName" />
                </a>
            </div>
        }
        <br />
        <div class="view-all-friends-link"><a href="#">View All Friends>></a></div>
    }
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_CustomerVideoAlbums.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.CustomerVideoAlbumModel

@{
   
    Html.AddScriptParts(ModelUtil.ContentPathMobSocial + "/common/jquery.form.js");
    Html.AddScriptParts(ModelUtil.ContentPathMobSocial + "/profile-pages/customer-video-albums.js");
}



<div id="dialog-ok"></div>

<div id="dialog-modal" class="add-video-dialog" title="Add Video">
    Enter the <i>embed url</i> of the video to add<br />
    
    (e.g. '//www.youtube.com/embed/abCDe1FghIj'):<br />
    

    <form id="addVideoForm" action="@Url.Action("SaveVideo", "MobSocial")" method="POST">
        <br/><br/>
        <input type="hidden" name="videoAlbumId" value="@Model.VideoAlbumId"/>
        <input type="text" title="Video Embed Url" placeholder="Video's Embed Url" name="videoUrl" value="" size="50" maxlength="800"/>
        
        @*    TODO: Add video preview thumbnail    *@

        <br/><br/>
    </form>

</div>

<div id="dialog-confirm" title="Delete Video?">Are you sure you want to delete this video?</div>


<div class="customer-album-container">
    
    @if (Model.IsCurrentUsersProfile)
    {
        <div class="add-video-button">
            <i class="fa fa-video-camera"></i>
            <span class="add-video-button-text" title="Add Video">Add Video</span>
        </div>
    }

    <h3 class="customer-album-description">Videos of @Model.CustomerFullName skating:</h3>
    <br/>

    @foreach (var item in Model.Videos)
    {
        <div class="customer-video-block" data-customerVideoId="@item.Id">
           
            <iframe width="560" height="315" 
                    src="@item.Url" frameborder="0" allowfullscreen>
            </iframe>

            <br/>
            <span class="customer-video-caption">@item.Caption</span>
            
            
            <div class="customer-video-tool-strip">
                @if (item.AlreadyLiked)
                {
                    <span class="customer-video-like-button disabled"><i class="fa fa-thumbs-up"></i><span class="text"> Liked</span></span>
                }
                else
                {
                    <span class="customer-video-like-button"><i class="fa fa-thumbs-up"></i><span class="text"> Like</span></span>
                }
                
                <span class="customer-video-likes @(!Model.IsCurrentUsersProfile ? "float-right-important" : "")"><i class="fa fa-thumbs-up"></i> <span class="customer-video-likecount" data-likeCount="@item.LikeCount">@item.LikeCount</span><span class="text"> Likes</span> </span>
                @if (Model.IsCurrentUsersProfile)
                {
                    <span class="delete-video-button" data-customerVideoId="@item.Id" title="Delete Video"><i class="fa fa-trash-o"></i> <span class="text"> Delete</span></span>
                }
            </div>
             
        </div>
    }
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_FeaturedVideosBlock.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.FeaturedVideosModel
<div class="block block-info">
    <div class="title">
        <strong>Featured Video</strong>
    </div>
    <div class="listbox">
        <ul class="list">
            @foreach (var item in Model.FeaturedVideos)
            {
                <span class="featured-video-item" data-customerProfileUrl="@(item.CustomerProfileUrl)?selectedTab=2">
                    <img src="@item.ThumbnailUrl" frameborder="0" allowfullscreen alt=""/>
                </span>
            }
        </ul>
    </div>
</div>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_MustLogin.cshtml
<p>Please <a href="/login">login</a> to continue</p>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/_TeamPageInfo.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.TeamPage.TeamPageModel

<div class="page team-page">
    <div class="page-body">
      
        <div class="team-container">
    
            <div class="team-picture">
                <img src="@Model.TeamPictureUrl" alt="@Model.TeamName" title="@Model.TeamName" />
            </div>
    
            <h1>@Model.TeamName</h1>

            <p class="team-description">@Model.TeamDescription</p>

            @foreach (var group in Model.Groups)
            {
                <h2>@group.Name</h2>
        
                foreach (var member in group.Members)
                {
                    <div class="team-member-picture">
                        <a href="@member.ProfileUrl">
                            <img src="@member.ThumbnailUrl" alt="@member.DisplayName" title="@member.DisplayName" />
                        </a>
                        @member.DisplayName
                    </div>
                }
        
                <p class="team-group-description">@group.Description</p>
        
            }
    


        </div>
    </div>
</div>