Nop.Plugin.Widgets.mobSocial/Controllers/Admin/ManageEventPageController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Widgets.MobSocial.Constants;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Web.Framework.Mvc.Filters;
using SeoExtensions = Nop.Plugin.WebApi.MobSocial.Extensions.SeoExtensions;

namespace Nop.Plugin.Widgets.MobSocial.Controllers.Admin
{
    public partial class ManageEventPageController : BaseAdminController
    {
        
        #region Fields
        private readonly IEventPageService _eventPageService;
        private readonly IPermissionService _permissionService;
        private readonly IWorkContext _workContext;
        private readonly IUrlRecordService _urlRecordService;
        private readonly ILocalizationService _localizationService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPictureService _pictureService;
        private readonly IEventPageHotelService _eventPageHotelService;
        #endregion

        #region Constructors

        public ManageEventPageController(IPermissionService permissionService,
            IEventPageService eventPageService,
            IWorkContext workContext,
            IUrlRecordService urlRecordService,
            ILocalizationService localizationService,
            ICustomerActivityService customerActivityService,
            IPictureService pictureService,
            IEventPageHotelService eventPageHotelService)
        {
            _permissionService = permissionService;
            _eventPageService = eventPageService;
            _workContext = workContext;
            _urlRecordService = urlRecordService;
            _localizationService = localizationService;
            _customerActivityService = customerActivityService;
            _pictureService = pictureService;
            _eventPageHotelService = eventPageHotelService;
        }

        #endregion

        #region Utilities

        //page not found
        public IActionResult PageNotFound()
        {
            this.Response.StatusCode = 404;
            this.Response.TrySkipIisCustomErrors = true;

            return View();
        }

     

        #endregion

        #region Methods

        [HttpPost]
        public IActionResult GetAll(DataSourceRequest command)
        {

            var entities = _eventPageService.GetAll();

            var models = new List<object>();

            foreach(var entity in entities)
            {
                var entityPicture = _eventPageService.GetFirstEntityPicture(entity.Id);
                var defaultPicture = (entityPicture != null) ? _pictureService.GetPictureById(entityPicture.PictureId) : null;

                var model = new {
                    Id = entity.Id,
                    PictureThumbnailUrl = _pictureService.GetPictureUrl(defaultPicture, 75, true),
                    Name = entity.Name,
                    Address = entity.LocationName + " " + entity.LocationAddress1 + " " + entity.LocationAddress2 + " " + 
                              entity.LocationCity + ", " + entity.LocationState + " " + 
                              entity.LocationZipPostalCode + " " + entity.LocationCountry,
                    LocationContactInfo = entity.LocationPhone + " " + entity.LocationEmail + " " + entity.LocationWebsite,
                    StartDate = entity.StartDate,
                    EndDate = entity.EndDate,
                    DateCreated = entity.DateCreated.ToString(),
                    DateUpdated = entity.DateUpdated.ToString(),
                };

                models.Add(model);
            }

            
            var gridModel = new DataSourceResult
            {
                Data = models,
                Total = entities.Count()
            };

            return Json(gridModel);
        }

        [AdminAuthorize]
        public IActionResult List()
        {
            return View(MobSocialConstant.ViewsPath + "/Views/mobSocial/Admin/ManageEventPage/List.cshtml");
        }

        [AdminAuthorize]
        public IActionResult Create()
        {
            // todo add permissions later
            //if (!_permissionService.Authorize(StandardPermissionProvider.ManageProducts))
            //    return AccessDeniedView();

            var model = new EventPageModel();
            return View(MobSocialConstant.ViewsPath + "/Views/mobSocial/Admin/ManageEventPage/Create.cshtml", model);
        }


        [AdminAuthorize]
        public IActionResult Edit(int id)
        {
            //todo: add later
            //if (!_permissionService.Authorize(MobSocialPermissionProvider.ManageEventPages))
            //    return AccessDeniedView();

            var item = _eventPageService.GetById(id);

            if (item == null) //Not found
                return RedirectToAction("List");


            var model = new EventPageModel()
            {
                Id = item.Id,
                Name = item.Name,
                SeName = SeoExtensions.GetSeName(item, _workContext.WorkingLanguage.Id),
                LocationName = item.LocationName,
                Address1 = item.LocationAddress1,
                Address2 = item.LocationAddress2,
                City = item.LocationCity,
                LocationState = item.LocationState,
                ZipPostalCode = item.LocationZipPostalCode,
                LocationCountry = item.LocationCountry,
                Phone = item.LocationPhone,
                Website = item.LocationWebsite,
                Email = item.LocationEmail,
                StartDate = item.StartDate,
                EndDate = item.EndDate,
                Description = item.Description,
                DateCreated = item.DateCreated,
                DateUpdated = item.DateUpdated,
                MetaDescription = item.MetaDescription,
                MetaKeywords = item.MetaKeywords,
                
            };

            return View(MobSocialConstant.ViewsPath + "/Views/mobSocial/Admin/ManageEventPage/Edit.cshtml", model);

        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public IActionResult Create(EventPageModel model, bool continueEditing)
        {
            //if (!_permissionService.Authorize(StandardPermissionProvider.ManageProducts))
            //    return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var entity = new EventPage()
                {
                    Name = model.Name,
                    LocationName = model.LocationName,
                    LocationAddress1 = model.LocationAddress1,
                    LocationAddress2 = model.LocationAddress2,
                    LocationCity = model.City,
                    LocationState = model.LocationState,
                    LocationZipPostalCode = model.ZipPostalCode,
                    LocationPhone = model.Phone,
                    LocationWebsite = model.Website,
                    LocationEmail = model.Email,
                    LocationCountry = model.LocationCountry,
                    StartDate = model.StartDate,
                    EndDate = model.EndDate,
                    Description = model.Description,
                    MetaKeywords = model.MetaKeywords,
                    MetaDescription = model.MetaDescription,
                    DateCreated = DateTime.Now,
                    DateUpdated = DateTime.Now,
                };

                //search engine name
                model.SeName = SeoExtensions.GetSeName(entity, _workContext.WorkingLanguage.Id);
             
                // todo: add event hosts
                _eventPageService.Insert(entity);

                //save hotels
                //SaveEventHotels(product, ParseProductTags(model.ProductTags));
                
                //activity log
                //_customerActivityService.InsertActivity("AddNewProduct", _localizationService.GetResource("ActivityLog.AddNewProduct"), product.Name);
                _customerActivityService.InsertActivity("AddNewEventPage", _localizationService.GetResource("ActivityLog.AddNewEventPage"), entity.Name);


                SuccessNotification(_localizationService.GetResource("Admin.MobSocial.EventPage.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = entity.Id }) : RedirectToAction("List");
            }

            return View(MobSocialConstant.ViewsPath + "/Views/mobSocial/Admin/ManageEventPage/Create.cshtml", model);

        }




        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public IActionResult Edit(EventPageModel model, bool continueEditing)
        {
            //todo: add later
            //if (!_permissionService.Authorize(MobSocialPermissionProvider.ManageEventPages))
            //    return AccessDeniedView();

            var item = _eventPageService.GetById(model.Id);
            if (item == null)
                //No product found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {


                item.Name = model.Name;
                item.LocationName = model.LocationName;
                item.LocationAddress1 = model.Address1;
                item.LocationAddress2 = model.Address2;
                item.LocationCity = model.City;
                item.LocationState = model.LocationState;
                item.LocationZipPostalCode = model.ZipPostalCode;
                item.LocationCountry = model.LocationCountry;
                item.LocationPhone = model.Phone;
                item.LocationWebsite = model.Website;
                item.LocationEmail = model.Email;
                item.StartDate = model.StartDate;
                item.EndDate = model.EndDate;
                item.Description = model.Description;

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/Admin/ManageEventPage/Create.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.EventPageModel
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    //page title
    ViewBag.Title = T("Admin.MobSocial.EventPage.AddNew").Text;
    
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "product-form" }))
{
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-catalog.png")" alt="" />
            @T("Admin.MobSocial.EventPage.AddNew") @Html.ActionLink("(" + T("Admin.MobSocial.EventPage.BackToList") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/Admin/ManageEventPage/Edit.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.EventPageModel
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    //page title
    ViewBag.Title = T("Admin.EventPage.EditDetails").Text;
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "eventpage-form" }))
{
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-catalog.png")" alt="" />
            @T("Admin.EventPage.EditDetails") - @Model.Name @Html.ActionLink("(" + T("Admin.EventPage.BackToList") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" value="@T("Admin.Common.Preview")" onclick="javascript:OpenWindow('@Url.RouteUrl("Product", new { SeName = Model.SeName })', 800, 600, true); return false;" class="k-button" />
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
            <input type="submit" id="copyproduct" name="copyproduct" class="k-button" value="@T("Admin.Catalog.Products.Copy")" />
            <span id="product-delete" class="k-button">@T("Admin.Common.Delete")</span>
        </div>
    </div>
    @Html.Partial("~/Plugins/Widgets.mobSocial/Views/mobSocial/Admin/ManageEventPage/_CreateOrUpdate.cshtml", Model)
}
@Html.DeleteConfirmation("product-delete")


<script type="text/javascript">
    $(document).ready(function () {
        $("#copyproduct").click(function (e) {
            e.preventDefault();
            var window = $("#copyproduct-window");
            if (!window.data("kendoWindow")) {
                window.kendoWindow({
                    modal: true,
                    width: "400px",
                    title: "@T("Admin.Catalog.Products.Copy")",
                    actions: ["Close"]
                });
            }
            window.data('kendoWindow').center().open();
        });
    });
</script>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/Admin/ManageEventPage/List.cshtml
@{    
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Manage Events";
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-configuration.png")" alt="" />
        Manage Events
    </div>
    <div class="options">
        <a href="@Url.Action("Create", "ManageEventPage")" class="k-button">@T("Admin.Common.AddNew")</a>
        <input type="button" id="delete-selected" class="k-button" value="@T("Admin.Common.Delete.Selected")" />
    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            <div id="grid"></div>
            <script>
                $(document).ready(function () {
                    $("#grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("GetAll", "ManageEventPage"))",
                                    type: "POST",
                                    dataType: "json"
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [
                                {
                                    field: "Id",
                                    headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: "<input type='checkbox' value='#=Id#' class='checkboxGroups'/>",
                                    width: 50
                                },
                            {

                                field: "PictureThumbnailUrl",
                                title: "@T("Admin.Catalog.Products.Fields.PictureThumbnailUrl")",
                                template: '<img src="#=PictureThumbnailUrl#" />',
                                width: 200
                            },
                            {
                                field: "Name",
                                title: "Name",
                                width: 250
                            }, {
                                field: "Address",
                                title: "Address",
                                width: 250,
                                template: '#=Address#<br>#=LocationContactInfo#'
                            }, {
                                field: "DateCreated",
                                title: "DateCreated",
                                width: 100,
                            }, {
                                field: "DateUpdated",
                                title: "DateUpdated",
                                width: 100,
                            },
                             {
                                 field: "Id",
                                 title: "Edit",
                                 width: 150,
                                 template: '<a href="Edit/#=Id#">Edit</a>'
                             }]
                    });
                });
            </script>
        </td>
    </tr>
</table>

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/Admin/ManageEventPage/_CreateOrUpdate.Hotels.cshtml
@model Nop.Plugin.WebApi.MobSocial.Models.EventPageModel


@if (Model.Id > 0)
{   
<table class="adminContent">
    <tr>
        <td>
            <div id="hotels-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#hotels-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("HotelList", "ManageEventPage", new { eventPageId = Model.Id }))",
                                    type: "POST",
                                    dataType: "json"
                                },
                                update: {
                                    url: "@Html.Raw(Url.Action("HotelUpdate", "ManageEventPage"))",
                                    type: "POST",
                                    dataType: "json"
                                },
                                destroy: {
                                    url: "@Html.Raw(Url.Action("HotelDelete", "ManageEventPage"))",
                                    type: "POST",
                                    dataType: "json"
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors",
                                model: {
                                    id: "Id",
                                    fields: {
                                        Id: { editable: false, type: "string" },
                                        DisplayOrder: {editable: true, type: "number" },
                                    }
                                }
                            },
                            requestEnd: function(e) {
                                if(e.type=="update") {
                                    this.read();
                                }
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "Name",
                            title: "Name"
                        }, {
                            field: "DisplayOrder",
                            title: "DisplayOrder",
                            width: 150
                        }, {
                            command: [{
                                name: "edit",
                                text: "@T("Admin.Common.Edit")"
                            }, {
                                name: "destroy",
                                text: "@T("Admin.Common.Delete")"
                            }],
                            width: 200
                        }]
                    });
                });
            </script>
        </td>
    </tr>

    <tr>
        <td width="100%">

            <p>
                <strong>@T("Admin.MobSocial.EventPage.Hotels.AddNew")</strong>
            </p>

            <script type="text/javascript">

                $(document).ready(function () {
                    $('#btnAddNew').click(function () {

                        var eventPageId = $("#@Html.FieldIdFor(model => model.Id)").val();
                        var title = $("#@Html.FieldIdFor(model => model.AddHotelModel.Title)").val();
                        var name = $("#@Html.FieldIdFor(model => model.AddHotelModel.Name)").val();
                        var address1 = $("#@Html.FieldIdFor(model => model.AddHotelModel.Address1)").val();
                        var address2 = $("#@Html.FieldIdFor(model => model.AddHotelModel.Address2)").val();
                        var city = $("#@Html.FieldIdFor(model => model.AddHotelModel.City)").val();
                        var state = $("#@Html.FieldIdFor(model => model.AddHotelModel.State)").val();
                        var zipPostalCode = $("#@Html.FieldIdFor(model => model.AddHotelModel.ZipPostalCode)").val();
                        var country = $("#@Html.FieldIdFor(model => model.AddHotelModel.Country)").val();
                        var phoneNumber = $("#@Html.FieldIdFor(model => model.AddHotelModel.PhoneNumber)").val();
                        var additionalInformation = tinyMCE.get('@Html.FieldIdFor(model => model.AddHotelModel.AdditionalInformation)').getContent();
                        var displayOrder = $("#@Html.FieldIdFor(model => model.AddHotelModel.DisplayOrder)").val();


                        var data = {
                            EventPageId: eventPageId,
                            Title: title,
                            Name: name,
                            Address1: address1,
                            Address2:  address2,
                            City:  city,
                            State:   state,
                            ZipPostalCode: zipPostalCode,
                            Country: country,
                            PhoneNumber: phoneNumber,
                            AdditionalInformation:   additionalInformation,
                            DisplayOrder:    displayOrder
                        };

                        $('#addNew').attr('disabled', true);

                        $.ajax({
                            cache:false,
                            type: "GET",
                            url: "@Url.Action("HotelAdd", "ManageEventPage")",
                            data: data,
                            success: function (data) {
                                var grid = $("#hotels-grid");
                                grid.data('kendoGrid').dataSource.read();
                                $('#addNew').attr('disabled', false);
                                return false;
                            },
                            error:function (xhr, ajaxOptions, thrownError){
                                alert('Failed to add hotel.');
                                $('#addNew').attr('disabled', false);
                                return false;
                            }
                        });
                    });
                });

            </script>

            <table class="adminContent">
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.Title):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.Title)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.Title)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.Name):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.Name)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.Name)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.Address1):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.Address1)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.Address1)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.Address2):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.Address2)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.Address2)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.City):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.City)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.City)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.State):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.State)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.State)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.ZipPostalCode):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.ZipPostalCode)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.ZipPostalCode)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.Country):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.Country)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.Country)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.PhoneNumber):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.PhoneNumber)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.AdditionalInformation):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.AdditionalInformation, "RichEditor")
                        @Html.ValidationMessageFor(model => model.AddHotelModel.AdditionalInformation)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.NopLabelFor(model => model.AddHotelModel.DisplayOrder):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.AddHotelModel.DisplayOrder)
                        @Html.ValidationMessageFor(model => model.AddHotelModel.DisplayOrder)
                    </td>
                </tr>

            </table>

        </td>
    </tr>


    <tr>
        <td width="100%">
            <input type="button" id="btnAddNew" name="btnAddNew" value="Add" class="k-button" />
            <input type="submit" id="btnRefresh" name="btnRefresh" style="display: none" />
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#btnRefresh').click(function () {
                        //refresh grid
                        var optionsGrid = $("#hotels-grid").data('kendoGrid');
                        optionsGrid.dataSource.read();

                        //return false to don't reload a page
                        return false;
                    });
                });
            </script>
        </td>
    </tr>
</table>
}
else
{
    @T("Admin.MobSocial.Common.SaveBeforeEdit")
}