Nop.Plugin.Widgets.mobSocial/Controllers/Admin/TeamPageController.cs
using Nop.Services.Security;

namespace Nop.Plugin.Widgets.MobSocial.Controllers.Admin
{
    public partial class TeamPageController : BaseAdminController
    {
        
        #region Fields
        private readonly ITeamPageService _teamPageService;
        private readonly IPermissionService _permissionService;
        #endregion

        #region Constructors

        public TeamPageController(IPermissionService permissionService, ITeamPageService teamPageService)
        {
            _permissionService = permissionService;
            _teamPageService = teamPageService;
        }

        #endregion


        #region Methods

        [AdminAuthorize]
        public IActionResult Index()
        {
            return View(ControllerUtil.MobSocialViewsFolder + "/Views/mobSocial/Admin/ManageTeamPage/List.cshtml");
        }
       
        #endregion


    }
}

Nop.Plugin.Widgets.mobSocial/Controllers/TeamPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Widgets.MobSocial.Models;

namespace Nop.Plugin.Widgets.MobSocial.Controllers
{
    public class TeamPageController : MobSocialWidgetBaseController
    {
        public IActionResult Index(int teamId)
        {
            var model = new TeamPageModel()
            {
                Id = teamId
            };
            return View("mobSocial/TeamPage/Index", model);
        }
        [Authorize]
        public IActionResult TeamPageEditor(int id = 0)
        {
            var model = new TeamPageEditorModel()
            {
                Id = id
            };

            return View("mobSocial/TeamPage/TeamPageEditor", model);
        }
        [Authorize]
        public IActionResult MyPages()
        {
            return View("mobSocial/TeamPage/MyPages");
        }
    }
}

Nop.Plugin.Widgets.mobSocial/Views/mobSocial/Admin/TeamPage/Index.cshtml
@{    
    ViewBag.Title = "Manage Teams";
}

<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-configuration.png")" alt="" />
        Manage Teams

    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            <div id="grid"></div>

            <script>
                $(document).ready(function () {
                    $("#grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("GetAll", "TeamPage"))",
                                    type: "POST",
                                    dataType: "json"
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "FriendlyName",
                            title: "@T("Admin.Configuration.Tax.Providers.Fields.FriendlyName")",
                            width: 250
                        }, {
                            field: "SystemName",
                            title: "@T("Admin.Configuration.Tax.Providers.Fields.SystemName")",
                            width: 250
                        }, {
                            field: "IsPrimaryTaxProvider",
                            title: "@T("Admin.Configuration.Tax.Providers.Fields.IsPrimaryTaxProvider")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IsPrimaryTaxProvider#.gif" />'
                        }, {
                            field: "SystemName",
                            title: "@T("Admin.Configuration.Tax.Providers.Fields.MarkAsPrimaryProvider")",
                            width: 200,
                            template: '<a href="@Url.Content("~/Admin/Tax/MarkAsPrimaryProvider/")?systemName=#=SystemName#" class="k-button">@T("Admin.Configuration.Tax.Providers.Fields.MarkAsPrimaryProvider")</a>'
                        }, {
                            field: "SystemName",
                            title: "@T("Admin.Configuration.Tax.Providers.Configure")",
                            width: 150,
                            template: '<a href="ConfigureProvider?systemName=#=SystemName#">@T("Admin.Configuration.Tax.Providers.Configure")</a>'
                        }]
                    });
                });
            </script>
        </td>
    </tr>
</table>